<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { IconSave as IconDownload, IconSearch } from '@arco-design/web-vue/es/icon'
import { api } from '../../services/api'
const rows = ref<any[]>([]); const ledger = ref<any[]>([]); const query = ref(''); const status = ref('all')
const filteredOrders = computed(() => rows.value.filter((x) => (status.value === 'all' || x.status === status.value) && (!query.value || `${x.id} ${x.user_name}`.toLowerCase().includes(query.value.toLowerCase())))); const revenue = computed(() => rows.value.filter((x) => x.status === 'paid').reduce((sum, x) => sum + Number(x.amount || 0), 0)); const recharged = computed(() => rows.value.filter((x) => x.status === 'paid').reduce((sum, x) => sum + Number(x.points || 0), 0)); const captured = computed(() => ledger.value.filter((x) => x.status === 'captured').reduce((sum, x) => sum + Number(x.amount || 0), 0)); const refunded = computed(() => ledger.value.filter((x) => x.status === 'refunded').reduce((sum, x) => sum + Number(x.amount || 0), 0))
async function load() { const [orders, transactions] = await Promise.all([api('/pay/admin/orders?limit=200'), api('/billing/ledger/admin?limit=200')]); if (orders.ok) rows.value = orders.data?.data || []; if (transactions.ok) ledger.value = transactions.data?.data || [] }
function exportCSV() { const fields = ['id', 'user_name', 'source', 'amount', 'points', 'pay_type', 'status', 'created_at']; const csv = [fields.join(','), ...filteredOrders.value.map((row) => fields.map((field) => `"${String(row[field] ?? '').replaceAll('"', '""')}"`).join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8' })); link.download = `northstar-orders-${Date.now()}.csv`; link.click(); URL.revokeObjectURL(link.href) }
onMounted(load); const columns = [{ title: '订单/交易', slotName: 'order', width: 230 }, { title: '用户', dataIndex: 'user_name' }, { title: '来源', slotName: 'source' }, { title: '金额', slotName: 'amount' }, { title: '额度变动', slotName: 'points' }, { title: '状态', slotName: 'status' }, { title: '时间', dataIndex: 'created_at' }]; const ledgerColumns = [{ title: '流水号', dataIndex: 'id' }, { title: '用户 ID', dataIndex: 'user_id' }, { title: '关联任务', dataIndex: 'event_id' }, { title: '用途', dataIndex: 'reason' }, { title: '额度', dataIndex: 'amount' }, { title: '状态', slotName: 'ledgerStatus' }, { title: '余额', dataIndex: 'balance_after' }]
</script>
<template><div><div class="section-heading"><div><h2>订单与账本</h2><p>支付、管理员调账、生成预留、确认扣费和退款。</p></div><a-button :disabled="!filteredOrders.length" @click="exportCSV"><IconDownload />导出账单</a-button></div><section class="billing-metrics"><div><span>已支付收入</span><strong>¥ {{ revenue.toFixed(2) }}</strong><small>{{ rows.filter(x => x.status === 'paid').length }} 笔订单</small></div><div><span>充值额度</span><strong>{{ recharged.toLocaleString() }}</strong><small>真实到账记录</small></div><div><span>已确认扣费</span><strong>{{ captured.toLocaleString() }}</strong><small>{{ ledger.filter(x => x.status === 'captured').length }} 笔流水</small></div><div><span>失败退款</span><strong>{{ refunded.toLocaleString() }}</strong><small>{{ ledger.filter(x => x.status === 'refunded').length }} 笔流水</small></div></section><div class="toolbar"><a-input v-model="query" placeholder="搜索订单号或用户"><template #prefix><IconSearch /></template></a-input><a-select v-model="status"><a-option value="all">全部状态</a-option><a-option value="paid">已支付</a-option><a-option value="pending">待支付</a-option><a-option value="cancelled">已取消</a-option></a-select></div><a-tabs default-active-key="ledger"><a-tab-pane key="ledger" title="生成账本"><a-table :columns="ledgerColumns" :data="ledger" :pagination="false"><template #ledgerStatus="{ record }"><a-tag :color="record.status === 'captured' ? 'green' : 'orange'">{{ record.status === 'captured' ? '已确认' : '已退款' }}</a-tag></template></a-table></a-tab-pane><a-tab-pane key="orders" title="充值订单"><a-table :columns="columns" :data="filteredOrders" :pagination="{ pageSize: 20, total: filteredOrders.length }"><template #order="{ record }"><div class="order"><strong>{{ record.id }}</strong><small>{{ record.pay_type }}</small></div></template><template #source="{ record }"><a-tag>{{ record.source || 'epay' }}</a-tag></template><template #amount="{ record }">¥ {{ Number(record.amount).toFixed(2) }}</template><template #points="{ record }"><strong class="positive">+{{ record.points }}</strong></template><template #status="{ record }"><a-tag :color="record.status === 'paid' ? 'green' : 'orange'">{{ record.status === 'paid' ? '已完成' : record.status === 'cancelled' ? '已取消' : '待支付' }}</a-tag></template></a-table></a-tab-pane></a-tabs></div></template>
<style scoped>.billing-metrics{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--ns-line);background:#fff;border-radius:var(--ns-radius);margin-bottom:18px}.billing-metrics>div{padding:18px 20px;border-right:1px solid var(--ns-line);display:flex;flex-direction:column}.billing-metrics>div:last-child{border:0}.billing-metrics span{font-size:10px;color:var(--ns-ink-soft)}.billing-metrics strong{font-size:20px;margin:8px 0 5px}.billing-metrics small{font-size:9px;color:var(--ns-accent)}.toolbar{display:grid;grid-template-columns:minmax(250px,360px) 150px;gap:10px;margin-bottom:14px}.order{display:flex;flex-direction:column}.order strong{font:11px ui-monospace}.order small{font-size:9px;color:var(--ns-ink-faint);margin-top:3px}.positive{color:var(--ns-accent-strong)}@media(max-width:800px){.billing-metrics{grid-template-columns:repeat(2,1fr)}.billing-metrics>div:nth-child(2){border-right:0}.billing-metrics>div:nth-child(-n+2){border-bottom:1px solid var(--ns-line)}.toolbar{grid-template-columns:1fr 140px}}
</style>
