<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Message, Modal } from '@arco-design/web-vue'
import { IconCheckCircle, IconDelete, IconPlus, IconStorage, IconThunderbolt } from '@arco-design/web-vue/es/icon'
import { api } from '../../services/api'

const loading=ref(false), importing=ref(false), importOpen=ref(false)
const rows=ref<any[]>([])
const form=reactive({keys:'',weight:0,concurrency:1})
async function load(){loading.value=true;const r=await api('/sanbao/accounts');loading.value=false;if(r.ok)rows.value=r.data.data||[];else Message.error(r.data?.detail||'加载失败')}
async function submit(){if(!form.keys.trim())return Message.warning('请粘贴 API Key');importing.value=true;const r=await api('/sanbao/accounts/import',{method:'POST',body:JSON.stringify(form)});importing.value=false;if(!r.ok)return Message.error(r.data?.detail||'导入失败');Message.success(`已导入 ${r.data.imported} 个账号`);if(r.data.failures?.length)Message.warning(`${r.data.failures.length} 个 Key 导入失败`);importOpen.value=false;form.keys='';load()}
async function test(row:any){row.testing=true;const r=await api(`/sanbao/accounts/${row.id}/test`,{method:'POST'});row.testing=false;if(r.ok)Message.success(`连接正常，可用额度 ${r.data.credits ?? '-'}`);else Message.error(r.data?.detail||'测试失败');load()}
async function toggle(row:any,value:boolean){const r=await api(`/sanbao/accounts/${row.id}`,{method:'PATCH',body:JSON.stringify({status:value?'active':'disabled'})});if(!r.ok)Message.error(r.data?.detail||'更新失败');load()}
async function saveLimits(row:any){const r=await api(`/sanbao/accounts/${row.id}`,{method:'PATCH',body:JSON.stringify({weight:Number(row.weight),concurrency:Number(row.concurrency)})});if(r.ok)Message.success('调度配置已保存');else Message.error(r.data?.detail||'保存失败')}
function remove(row:any){Modal.warning({title:'删除三宝账号',content:`确认删除 ${row.name||row.key_preview}？进行中的任务不会切换账号。`,hideCancel:false,onOk:async()=>{const r=await api(`/sanbao/accounts/${row.id}`,{method:'DELETE'});if(r.ok){Message.success('账号已删除');load()}else Message.error(r.data?.detail||'删除失败')}})}
function fmt(v:any){if(!v)return '从未调用';return new Date(v).toLocaleString('zh-CN',{hour12:false})}
onMounted(load)
</script>
<template><div class="admin-page"><div class="section-heading"><div><h2>三宝账号</h2><p>管理视频生成 API Key、上游额度与轮询调度。</p></div><a-button type="primary" @click="importOpen=true"><IconPlus/>批量导入</a-button></div>
<div class="summary"><div><span class="summary-icon"><IconStorage/></span><p><small>账号总数</small><strong>{{ rows.length }}</strong></p></div><div><span class="summary-icon good"><IconCheckCircle/></span><p><small>可用账号</small><strong>{{ rows.filter(x=>x.status==='active'&&!x.dead).length }}</strong></p></div><div><span class="summary-icon warm"><IconThunderbolt/></span><p><small>正在执行</small><strong>{{ rows.reduce((n,x)=>n+Number(x.inflight||0),0) }}</strong></p></div></div>
<div class="table-shell"><a-table :data="rows" :loading="loading" row-key="id" :pagination="false" :scroll="{x:1100}"><template #columns>
<a-table-column title="账号" :width="230"><template #cell="{record}"><div class="identity"><span>{{ (record.name||'三宝').slice(0,1) }}</span><div><strong>{{ record.name||'三宝账号' }}</strong><small>{{ record.email||record.key_preview }}</small></div></div></template></a-table-column>
<a-table-column title="状态" :width="100"><template #cell="{record}"><span class="status" :class="record.status"><i></i>{{ record.dead?'失效':record.status==='active'?'可用':'停用' }}</span></template></a-table-column>
<a-table-column title="上游额度" :width="110"><template #cell="{record}"><strong>{{ record.credits ?? '-' }}</strong></template></a-table-column>
<a-table-column title="任务" :width="130"><template #cell="{record}"><span class="task-stat">执行 {{ record.inflight||0 }} · 成功 {{ record.success_total||0 }}</span></template></a-table-column>
<a-table-column title="权重 / 并发" :width="190"><template #cell="{record}"><div class="limits"><a-input-number v-model="record.weight" :min="0" :max="100" size="small"/><a-input-number v-model="record.concurrency" :min="1" :max="20" size="small"/><button @click="saveLimits(record)">保存</button></div></template></a-table-column>
<a-table-column title="最后调用" :width="180"><template #cell="{record}"><span class="muted">{{ fmt(record.last_used_at) }}</span></template></a-table-column>
<a-table-column title="操作" :width="160" fixed="right"><template #cell="{record}"><div class="actions"><a-switch :model-value="record.status==='active'&&!record.dead" size="small" @change="toggle(record,Boolean($event))"/><a-tooltip content="测试连接"><button @click="test(record)"><IconCheckCircle/></button></a-tooltip><a-tooltip content="删除"><button class="danger" @click="remove(record)"><IconDelete/></button></a-tooltip></div></template></a-table-column>
</template><template #empty><a-empty description="尚未导入三宝 API Key"/></template></a-table></div>
<a-modal v-model:visible="importOpen" title="批量导入三宝 API Key" :ok-loading="importing" ok-text="校验并导入" @ok="submit"><div class="import-form"><label>API Key（一行一个）</label><a-textarea v-model="form.keys" :auto-size="{minRows:7,maxRows:12}" placeholder="sk_sanbao_xxx&#10;sk_sanbao_xxx"/><div class="form-grid"><div><label>调度权重</label><a-input-number v-model="form.weight" :min="0" :max="100"/></div><div><label>单账号并发</label><a-input-number v-model="form.concurrency" :min="1" :max="20"/></div></div><p>导入时会真实请求三宝账户接口，只有有效 Key 才会写入账号池。</p></div></a-modal>
</div></template>
<style scoped>
.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:18px}.summary>div{height:84px;display:flex;align-items:center;gap:13px;padding:0 18px;border:1px solid var(--ns-line);border-radius:7px;background:#fff}.summary-icon{width:36px;height:36px;display:grid;place-items:center;border-radius:50%;background:#e7ebe4;color:#53604f}.summary-icon.good{background:#e4ece1;color:#4f674b}.summary-icon.warm{background:#f3ecd4;color:#967c25}.summary p{display:flex;flex-direction:column;margin:0}.summary small{font-size:10px;color:var(--ns-ink-faint)}.summary strong{margin-top:3px;font-size:19px}.table-shell{overflow:hidden;border:1px solid var(--ns-line);border-radius:7px;background:#fff}.identity{display:flex;align-items:center;gap:10px}.identity>span{width:32px;height:32px;display:grid;place-items:center;border-radius:50%;background:#e3e8df;color:#4e5c49;font-weight:700}.identity div{min-width:0;display:flex;flex-direction:column}.identity strong{font-size:11px}.identity small,.muted,.task-stat{margin-top:3px;color:var(--ns-ink-faint);font-size:9px}.status{display:inline-flex;align-items:center;gap:6px;font-size:10px}.status i{width:7px;height:7px;border-radius:50%;background:#aaa}.status.active i{background:#6f8767}.limits{display:grid;grid-template-columns:58px 58px 45px;gap:5px}.limits button{border:1px solid var(--ns-line);border-radius:5px;background:#fff;font-size:9px;cursor:pointer}.actions{display:flex;align-items:center;gap:9px}.actions button{width:28px;height:28px;display:grid;place-items:center;border:1px solid var(--ns-line);border-radius:50%;background:#fff;color:var(--ns-ink-soft);cursor:pointer}.actions button.danger{color:#9b5e51}.import-form label{display:block;margin-bottom:7px;font-size:11px;font-weight:650}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:14px}.form-grid :deep(.arco-input-number){width:100%}.import-form p{margin:14px 0 0;color:var(--ns-ink-faint);font-size:10px;line-height:1.6}@media(max-width:700px){.summary{grid-template-columns:1fr}.summary>div{height:68px}}
</style>
