<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Message } from '@arco-design/web-vue'
import { IconMore, IconPlus, IconSearch } from '@arco-design/web-vue/es/icon'
import { api } from '../../services/api'
const rows = ref<any[]>([]); const total = ref(0); const query = ref(''); const role = ref('all'); const createOpen = ref(false); const creditOpen = ref(false); const saving = ref(false); const selected = ref<any>(null); const createForm = reactive({ username: '', email: '', password: '', role: 'user', credits: 0 }); const creditForm = reactive({ delta: 0 })
const filtered = computed(() => rows.value.filter((x) => (role.value === 'all' || x.role === role.value) && (!query.value || `${x.name} ${x.email} ${x.id}`.toLowerCase().includes(query.value.toLowerCase()))))
async function load() { const response = await api('/users?limit=200'); if (response.ok) { rows.value = response.data?.data || []; total.value = response.data?.total || rows.value.length } }
async function createUser() { saving.value = true; const response = await api('/users', { method: 'POST', body: JSON.stringify(createForm) }); saving.value = false; if (!response.ok) return Message.error(response.data?.detail || '创建用户失败'); createOpen.value = false; Object.assign(createForm, { username: '', email: '', password: '', role: 'user', credits: 0 }); await load(); Message.success('用户已创建') }
function adjust(row: any) { selected.value = row; creditForm.delta = 0; creditOpen.value = true }
async function saveCredits() { saving.value = true; const response = await api(`/users/${selected.value.id}/credits`, { method: 'POST', body: JSON.stringify({ delta: Number(creditForm.delta) }) }); saving.value = false; if (!response.ok) return Message.error(response.data?.detail || '额度调整失败'); creditOpen.value = false; await load(); Message.success('额度已调整') }
async function toggleStatus(row: any) { const next = row.status === 'active' ? 'disabled' : 'active'; const response = await api(`/users/${row.id}`, { method: 'PATCH', body: JSON.stringify({ status: next }) }); if (!response.ok) return Message.error(response.data?.detail || '状态更新失败'); await load(); Message.success('用户状态已更新') }
onMounted(load); const columns = [{ title: '用户', slotName: 'user', width: 270 }, { title: '角色', slotName: 'role' }, { title: '可用额度', dataIndex: 'credits' }, { title: '累计生成', dataIndex: 'generation_count' }, { title: '状态', slotName: 'status' }, { title: '注册时间', dataIndex: 'created_at' }, { title: '', slotName: 'actions' }]
</script>
<template><div><div class="section-heading"><div><h2>用户与权限</h2><p>管理用户状态、角色和可用额度。</p></div><a-button type="primary" @click="createOpen = true"><IconPlus />新建用户</a-button></div><div class="toolbar"><a-input v-model="query" placeholder="搜索用户名、邮箱或 ID"><template #prefix><IconSearch /></template></a-input><a-select v-model="role"><a-option value="all">全部角色</a-option><a-option value="user">普通用户</a-option><a-option value="agent">代理</a-option><a-option value="admin">管理员</a-option></a-select><span>{{ filtered.length }} / {{ total }}</span></div><a-table :columns="columns" :data="filtered" :pagination="{ total: filtered.length, pageSize: 20 }" row-key="id"><template #user="{ record }"><div class="user-cell"><a-avatar :size="34" :style="{ background: '#e1e6dd', color: '#3f4f3a' }">{{ record.name?.slice(0, 1) }}</a-avatar><div><strong>{{ record.name }}</strong><small>{{ record.email }} · {{ record.id }}</small></div></div></template><template #role="{ record }"><a-tag>{{ record.role === 'admin' ? '管理员' : record.role === 'agent' ? '代理' : '用户' }}</a-tag></template><template #status="{ record }"><span class="status"><i :class="{ off: record.status !== 'active' }"></i>{{ record.status === 'active' ? '正常' : '禁用' }}</span></template><template #actions="{ record }"><a-dropdown><a-button type="text" title="更多操作"><IconMore /></a-button><template #content><a-doption @click="adjust(record)">调整额度</a-doption><a-doption @click="toggleStatus(record)">{{ record.status === 'active' ? '禁用账户' : '启用账户' }}</a-doption></template></a-dropdown></template></a-table><a-modal v-model:visible="createOpen" title="新建用户" :ok-loading="saving" @ok="createUser"><a-form :model="createForm" layout="vertical"><a-form-item label="用户名"><a-input v-model="createForm.username" /></a-form-item><a-form-item label="邮箱"><a-input v-model="createForm.email" /></a-form-item><a-form-item label="初始密码"><a-input-password v-model="createForm.password" /></a-form-item><div class="form-grid"><a-form-item label="角色"><a-select v-model="createForm.role"><a-option value="user">用户</a-option><a-option value="agent">代理</a-option><a-option value="admin">管理员</a-option></a-select></a-form-item><a-form-item label="初始额度"><a-input-number v-model="createForm.credits" :min="0" /></a-form-item></div></a-form></a-modal><a-modal v-model:visible="creditOpen" title="调整额度" :ok-loading="saving" @ok="saveCredits"><p class="modal-hint">当前用户：{{ selected?.name }}，正数增加额度，负数扣减额度。</p><a-input-number v-model="creditForm.delta" /></a-modal></div></template>
<style scoped>.toolbar{display:grid;grid-template-columns:minmax(260px,380px) 150px 1fr;gap:10px;align-items:center;margin-bottom:14px}.toolbar>span{text-align:right;color:var(--ns-ink-faint);font-size:11px}.user-cell{display:flex;align-items:center;gap:10px}.user-cell>div{display:flex;flex-direction:column;min-width:0}.user-cell strong{font-size:11px}.user-cell small{font-size:9px;color:var(--ns-ink-faint);margin-top:3px;white-space:nowrap}.status{display:flex;align-items:center;gap:6px;font-size:11px}.status i{width:6px;height:6px;border-radius:50%;background:#65735d}.status i.off{background:#b75b4b}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.modal-hint{font-size:12px;color:var(--ns-ink-soft)}@media(max-width:650px){.toolbar{grid-template-columns:1fr 130px}.toolbar>span{display:none}}
</style>
