<script setup lang="ts">
import { reactive, ref } from 'vue'
import { Message } from '@arco-design/web-vue'
import { useAuthStore } from '../../stores/auth'
import { api } from '../../services/api'
const auth = useAuthStore(); const passwordOpen = ref(false); const busy = ref(false); const form = reactive({ current: '', next: '', confirm: '' })
async function changePassword() { if (!form.current || !form.next || form.next !== form.confirm) return Message.warning('请完整填写并确认新密码'); busy.value = true; const response = await api('/auth/change-password', { method: 'POST', body: JSON.stringify({ current_password: form.current, new_password: form.next }) }); busy.value = false; if (!response.ok) return Message.error(response.data?.detail || '密码修改失败'); passwordOpen.value = false; Object.assign(form, { current: '', next: '', confirm: '' }); Message.success('密码已更新，请重新登录') }
</script>
<template><div class="settings-page"><div class="section-heading"><div><h2>账户设置</h2><p>管理账户身份和登录安全。</p></div></div><section><div class="section-title"><h3>个人资料</h3><p>当前资料由服务端账户信息提供。</p></div><div class="profile-card"><a-avatar :size="52" :style="{ background: '#dfe7da', color: '#3f4f3a' }">{{ auth.user?.name?.slice(0, 1) || 'N' }}</a-avatar><div><strong>{{ auth.user?.name || '未设置名称' }}</strong><span>{{ auth.user?.email }}</span><small>角色：{{ auth.user?.role || 'user' }}</small></div></div></section><section><div class="section-title"><h3>账户安全</h3><p>密码变更后其他登录会话需要重新验证。</p></div><div><div class="security-row"><div><strong>登录密码</strong><small>使用服务端接口安全更新</small></div><a-button @click="passwordOpen = true">修改密码</a-button></div><div class="security-row"><div><strong>当前会话</strong><small>退出后本设备令牌立即失效</small></div><a-button status="danger" @click="auth.logout">退出登录</a-button></div></div></section><a-modal v-model:visible="passwordOpen" title="修改密码" modal-class="user-dialog" :ok-loading="busy" @ok="changePassword"><a-form :model="form" layout="vertical"><a-form-item label="当前密码"><a-input-password v-model="form.current" /></a-form-item><a-form-item label="新密码"><a-input-password v-model="form.next" /></a-form-item><a-form-item label="确认新密码"><a-input-password v-model="form.confirm" /></a-form-item></a-form></a-modal></div></template>
<style scoped>.settings-page{max-width:900px}.settings-page section{display:grid;grid-template-columns:230px 1fr;gap:36px;padding:28px 0;border-top:1px solid var(--ns-line)}.section-title h3{margin:0 0 6px;font-size:14px}.section-title p{margin:0;color:var(--ns-ink-soft);font-size:11px;line-height:1.6}.profile-card{display:flex;align-items:center;gap:14px}.profile-card div{display:flex;flex-direction:column}.profile-card strong{font-size:14px}.profile-card span,.profile-card small{margin-top:4px;color:var(--ns-ink-soft);font-size:11px}.profile-card small{color:var(--ns-ink-faint)}.security-row{display:flex;align-items:center;justify-content:space-between;padding:15px 0;border-bottom:1px solid var(--ns-line)}.security-row>div{display:flex;flex-direction:column}.security-row strong{font-size:12px}.security-row small{font-size:10px;color:var(--ns-ink-faint);margin-top:4px}@media(max-width:700px){.settings-page section{grid-template-columns:1fr;gap:18px}}
</style>
